### ISSUE TITLE
From feature vector to mask

### ISSUE THREAD

**Issue by mcamila777** [iyah4888/SIGGRAPH18SSS#1]
Hi,

I followed your installation tutorial in the readme and I got the 128-dimensional feature vector per pixel for a given image. But I can not find the code for filtering each of the 128 dimensions with guided filter and applying the dimensionality reduction with PCA to 3 in order to get the segmentation mask. 

Is it possible that you upload this code? and could you please give more details about how to get each segmented object (mask) from this feature vector?

Thanks!

**Comment by yaksoy** [comment]
Hey,

Please see the spectral segmentation implementation here: 
https://github.com/yaksoy/SemanticSoftSegmentation

The filtering / PCA part is also included there.

**Comment by bombs-kim** [comment]
@yaksoy Could you please specify the steps to follows in detail? That github project doesn't contain any guideline.

**Comment by BTUJACK** [comment]
> Hi,
> 
> I followed your installation tutorial in the readme and I got the 128-dimensional feature vector per pixel for a given image. But I can not find the code for filtering each of the 128 dimensions with guided filter and applying the dimensionality reduction with PCA to 3 in order to get the segmentation mask.
> 
> Is it possible that you upload this code? and could you please give more details about how to get each segmented object (mask) from this feature vector?
> 
> Thanks!

if you want to test your own png type pictures, you may have to obey the following instructions:

firstly, you have to use the python code to generate the 128-dimensional feature vector in [Github - SIGGRAPH18SSS - Semantic feature generator;

secondly, you should  reduce the dimension of features from 128 to 3 which uses the matlab code  in  a file named preprocessFeatures.m in [Github - Spectral segmentation implementation.

thirdly, you have to combine the  3-dimensional features(png picture) with the original picture to generate the target picture.

if you still have any problem about this paper, do not hesitate to contact me via email: stevejobsjack@gmail.com
