### ISSUE TITLE
what can I do to replace the train datasets?

### ISSUE THREAD

**Issue by zhouyuan888888** [iyah4888/SIGGRAPH18SSS#10]
In your paper , the train datasets is COCO-Stuff datasets, but I want to use other datasets to train the model , and test the results of the model ,what can I do ?

**Comment by iyah4888** [comment]
The repository does not include train codes; thus, you need to implement codes for training.
Also, please check "Credits" in the front page documentation of this repository, which will give you the point to refer for the implementation.

**Comment by zhouyuan888888** [comment]
thank you very much~
