### ISSUE TITLE
How to run “run_extract_feat.sh” file in Windows 10？

### ISSUE THREAD

**Issue by ghost** [iyah4888/SIGGRAPH18SSS#17]
How to run “run_extract_feat.sh” file in Windows 10？

**Comment by JohnMath3w** [comment]
Open Git Bash in the directory and run "sh run_extract_feat.sh"

**Comment by iyah4888** [comment]
Thanks @JohnMath3w for the kind response.
Yes, zxq2233, you can use the window bash tools.  Or you can even run the actual code in the shell script. It's not a big deal.
Please search for the information on Google.
