### ISSUE TITLE
Remove Background

### ISSUE THREAD

**Issue by makaveli10** [iyah4888/SIGGRAPH18SSS#22]
After generating the 128 dim feature vector. How to proceed to remove background alpha from the image, I just need some direction. After that I have been successful in generating the segmentation using demo.png but still confused if its using the docia.mat file or docia.png file to generate segmentation. 
![fig](https://user-images.githubusercontent.com/39617050/75790575-64bd7380-5d91-11ea-8473-13803c342814.png)

Please give a direction to proceed in order to remove the background alphas from this image.

**Comment by makaveli10** [comment]
I have been able to generate this after playing around the code:

    for i = 2 : 2
        vis = repmat(softSegments(:,:,i), [1 1 3]);
    end

![trimap](https://user-images.githubusercontent.com/39617050/75853835-e1ddfc80-5e14-11ea-8aa2-e2aeaf5c9e7d.png)

But how to map it to the original image and remove backgorund? thats what I am stuck at. Need help
Please let me know if this is the right way to proceed?

**Comment by anish6400** [comment]
> I have been able to generate this after playing around the code:
> 
> ```
> for i = 2 : 2
>     vis = repmat(softSegments(:,:,i), [1 1 3]);
> end
> ```
> 
> ![trimap](https://user-images.githubusercontent.com/39617050/75853835-e1ddfc80-5e14-11ea-8aa2-e2aeaf5c9e7d.png)
> 
> But how to map it to the original image and remove backgorund? thats what I am stuck at. Need help
> Please let me know if this is the right way to proceed?

which code you tweaked here? let me know please

**Comment by anish6400** [comment]
> I have been able to generate this after playing around the code:
> 
> ```
> for i = 2 : 2
>     vis = repmat(softSegments(:,:,i), [1 1 3]);
> end
> ```
> 
> ![trimap](https://user-images.githubusercontent.com/39617050/75853835-e1ddfc80-5e14-11ea-8aa2-e2aeaf5c9e7d.png)
> 
> But how to map it to the original image and remove backgorund? thats what I am stuck at. Need help
> Please let me know if this is the right way to proceed?

Bro can you help me please, how you got this from mat file?

**Comment by makaveli10** [comment]
@AnishKumar0285 please go to the visualiswSoftSegments.m file and change to the mentioned code

    for i = 2 : 2
        vis = repmat(softSegments(:,:,i), [1 1 3]);
    end

**Comment by iyah4888** [comment]
When you have an alpha map a, you can composite a new image I from two different images A & B by 

I = a*A+(1-a)*B
