### ISSUE TITLE
Getting different results!!!!

### ISSUE THREAD

**Issue by zq649** [iyah4888/SIGGRAPH18SSS#4]
Hi,
I used your semantic feature generation code to generate the features of the images 'docia.png'. But I am facing difference in the results. Please see the images below and guide me if I am doing anything wrong. You can see the difference in the features generated. After getting the feature vector I am feeding that vector to 'preprocessFeatures.m' file. Is there something else that I need to do?

In this picture I generated the feature through the code and then fed the image as input in demo.m file.
![outsamp](https://user-images.githubusercontent.com/37440553/45267902-5dfcbb80-b48e-11e8-957d-ca448d457e15.png)

This result is generated by the image you provided as docia.png
![untitled1](https://user-images.githubusercontent.com/37440553/45267901-4fae9f80-b48e-11e8-82ed-61858ec0dc34.png)

**Comment by minizon** [comment]
I think the different softsegments may due to the randomness in k-means. However the reduced feature map generated by HyperColumn_Deeplabv2 is still different from the given png image.
![untitled](https://user-images.githubusercontent.com/11333107/45464278-6ed55780-b742-11e8-85c4-99a921af017c.png)
![untitled1](https://user-images.githubusercontent.com/11333107/45464283-7432a200-b742-11e8-9a1f-9cd061453f2b.png)

**Comment by yaksoy** [comment]
Hi,

Yes, there's randomness due to k-means and each run may give you slightly different results. I'm not sure why the features you get are worse than we got, though. I'll try to have a look into it.

Yagiz

**Comment by iyah4888** [comment]
Hi sorry for this late response.
I have fully occupied these days. Let me try to find a time for testing this.

**Comment by cquptlxf** [comment]
How do you transform the form of mat into the form of png?Can you tell me?Thank you~

**Comment by texastone** [comment]
I had very similar feature images to minizon which was created by saving the figure into a png file.
I also tried to increase the dimension of features to 10. In both cases, the balloon and the collar of the shirt were having the same color - they were classified into the same segment. 
![docia-myresults](https://user-images.githubusercontent.com/31946638/49261048-fd827800-f405-11e8-8cd0-6c882bfaf003.jpg)
![docia-myresults-10](https://user-images.githubusercontent.com/31946638/49261066-1be87380-f406-11e8-94f4-4046334bd0cf.jpg)

**Comment by Diligentfight** [comment]
Maybe just the pretrained model have some problem？

**Comment by jack155861** [comment]
> ow do you transform the form of mat into the form of png?Can you tell me?Thank you~

import matplotlib.pyplot as plt
import scipy.io
mat = scipy.io.loadmat('Feat/docia.mat')
i=0
plt.imshow(mat['embedmap'][:, :, i])

w=600
h=600
fig=plt.figure(figsize=(100, 100))
columns = 8
rows = 20
for i in range(1,129):
    fig.add_subplot(rows, columns, i)
    plt.imshow(mat['embedmap'][:, :, i-1])
plt.show()

**Comment by yaksoy** [comment]
> > ow do you transform the form of mat into the form of png?Can you tell me?Thank you~
> 
> import matplotlib.pyplot as plt
> import scipy.io
> mat = scipy.io.loadmat('Feat/docia.mat')
> i=0
> plt.imshow(mat['embedmap'][:, :, i])
> 
> w=600
> h=600
> fig=plt.figure(figsize=(100, 100))
> columns = 8
> rows = 20
> for i in range(1,129):
> fig.add_subplot(rows, columns, i)
> plt.imshow(mat['embedmap'][:, :, i-1])
> plt.show()

This is not the way to transform the .mat file for the semantic features to png. Please use the dimension reduction function in the sister repository with the spectral segmentation implementation. The result from this is a double in [0,1] with 3 channels. Just save that as the png.

**Comment by sde123** [comment]
@yaksoy 
Hi yaksoy
Could you tell me where I can find this dimension reduction function。 I do not know what is the sister repository。Thank you very much！

**Comment by sde123** [comment]
@qasimz 
Hi
Could you tell me how do you transform the form of mat into the form of png？Tjank you very much！

**Comment by sde123** [comment]
@minizon 
Hi
Could you tell me how do you transform the form of mat into the form of png？Tjank you very much！

**Comment by ZOUCharles** [comment]
> > > ow do you transform the form of mat into the form of png?Can you tell me?Thank you~
> > 
> > 
> > import matplotlib.pyplot as plt
> > import scipy.io
> > mat = scipy.io.loadmat('Feat/docia.mat')
> > i=0
> > plt.imshow(mat['embedmap'][:, :, i])
> > w=600
> > h=600
> > fig=plt.figure(figsize=(100, 100))
> > columns = 8
> > rows = 20
> > for i in range(1,129):
> > fig.add_subplot(rows, columns, i)
> > plt.imshow(mat['embedmap'][:, :, i-1])
> > plt.show()
> 
> This is not the way to transform the .mat file for the semantic features to png. Please use the dimension reduction function in the sister repository with the spectral segmentation implementation. The result from this is a double in [0,1] with 3 channels. Just save that as the png.

could you please add a link to the repository/file mentioned above? tks!

**Comment by iyah4888** [comment]
Please check near this code line.
https://github.com/yaksoy/SemanticSoftSegmentation/blob/fb89f498ebdefa19f5f5fc4a639a9ff190ac09e5/SemanticSoftSegmentation.m#L13

**Comment by makaveli10** [comment]
Cannot run it in octave. Please tell me if this code is compatible with octave or we can only run it in matlab.
