### ISSUE TITLE
OOM ERROR

### ISSUE THREAD

**Issue by ns2mitu** [iyah4888/SIGGRAPH18SSS#5]
Hi,
I follow your guide and run the model to predict './samples/docia.png', but i get a out of memory error ...
The error message says there is no free memory , and the memory does be exhausted when I monitor GPU status.
I use Nvidia GTX 1060 6G with  ubuntu 18.04 .
If possible , can you tell me how many memorys do you use for predict?
thanks.

**Comment by ns2mitu** [comment]
I resolve the problem by use CPU . And GPU method is still not resovled.

**Comment by iyah4888** [comment]
The code is only tested with Titan Xp. Not guaranteed with 1060 which has just a half memory of it.
