### ISSUE TITLE
Error: 'images' contains no shape.

### ISSUE THREAD

**Issue by Dyson-Ido** [iyah4888/SIGGRAPH18SSS#8]
Hi,
  I have this error as below:

```
$ CUDA_VISIBLE_DEVICES=0 python main_hyper.py --data-dir ./samples
2018-10-10 10:11:47.248664: I C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
 [*] Loading checkpoints...
 [!] Load failed...
0 Processing ./samples\docia.png
Traceback (most recent call last):
  File "main_hyper.py", line 113, in <module>
    _, ori_img = read_img(local_imgflist[i], input_size = None, img_mean = IMG_MEAN)
  File "main_hyper.py", line 79, in read_img
    img2 = tf.image.resize_images(img, tf.shape(img)[0:2,]*2)
  File "D:\Python36\lib\site-packages\tensorflow\python\ops\image_ops_impl.py", line 741, in resize_images
    raise ValueError('\'images\' contains no shape.')
ValueError: 'images' contains no shape.
```

**Comment by BTUJACK** [comment]
hi, yang,
maybe you have to download mode firstly and you have to close you GPU  when you use windows system.

**Comment by Senyao-Han** [comment]
I had the same error and I downloaded old repository. Problem solved.

**Comment by gsygsy96** [comment]
Have you solved your problem?

**Comment by Dyson-Ido** [comment]
> hi, yang,
> maybe you have to download mode firstly and you have to close you GPU when you use windows system.

I download pre-trained model. But in your description it works on windows with GPU.

**Comment by Dyson-Ido** [comment]
> Have you solved your problem?

Not yet.

**Comment by gsygsy96** [comment]
You can download precious version code

**Comment by void-main** [comment]
@Senyao-Han Where is the old repository?

**Comment by void-main** [comment]
Changed back to `tf.image.decode_png` in `main_hyper.py` at line 65 solved the problem.

**Comment by iyah4888** [comment]
Sorry for making this problem.
I edited that part and stopped testing it due to a lot of hassles.
Let me roll back to the original code and after this CVPR, I will update it.
Before that time, any contribution will be welcome!
