### ISSUE TITLE
How to transform mat into PNG?

### ISSUE THREAD

**Issue by mengxiabing** [iyah4888/SIGGRAPH18SSS#9]
How to transform mat into PNG? How to reduce dimensions?

**Comment by lianuo** [comment]
it seems that we need to complete the late step by ourself

**Comment by sklipnoty** [comment]
Same problem.

**Comment by yaksoy** [comment]
Please see the accompanying spectral segmentation repo for the dimension reduction.

**Comment by ghost** [comment]
@mengxiabing @lianuo @sklipnoty in case you haven't figured it out. After reshaping the mat['embedmap'] from (height, width, dimensions) to (height*width, dimensions) . Just use PCA to lower the dimension to 3 and then perform min-max normalization.
